name: walk

on:
  # push:  # 代码推送到仓库时触发
    # branches: [ main ] 
  # pull_request: # Pull Request 创建或更新时触发
    # branches: [ main ]
  schedule:
    - cron: 27 2 * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v2
      - name: 初始化Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: 开始
        run: |
          pip install requests
          pmode='${{ secrets.PMODE }}'
          pkey='${{ secrets.PKEY }}'
          user='${{ secrets.USER8019 }}'
          pwd='${{ secrets.PWD8019 }}'
          step='${{ secrets.STEP }}'

          python3 main.py ${pmode} ${pkey} ${user} ${pwd} ${step}
